#include "lcd.h"
#include <mcpi2c.h>

static void lcdEN_Strobe(void);
static void lcdSendCommand(UINT8);
static void lcdSendData(UINT8);
static void lcdSendByte(UINT8);

// Puts a charachter on LCD
#define lcdPutChar(x) lcdSendData(x)

// LCD Function
void lcdInit(void)
{
    UINT8 iNdx,iTmp;

    //Delay_ms(5);

    // Reset Sequence
    LCD_EN = 0;
    LCD_RS = 0;

    // Enter in 4 bit mode
    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | 0x03;
    mcpWrite(GPIO,iTmp);
    for(iNdx=1;iNdx<=3;iNdx++)
    {
        lcdEN_Strobe();
        //Delay_ms(5);
    }

    iTmp = (iTmp & 0xF0) | 0x02;
    mcpWrite(GPIO,iTmp);
    lcdEN_Strobe();

    lcdSendCommand(0x28); // 4-bit mode, 2 lines display, font 5x8 pixels
    lcdSendCommand(0x06); // Increment, no shift

    // Display ON, Cursor OFF, Blink OFF
    lcdSendCommand(0x0C);
    lcdSendCommand(0x01);
    lcdSendCommand(0x03);
}

// Moves the cursor to ("row", "column") position
void lcdGotoXY(UINT8 x, UINT8 y)
{
    UINT8 chByte;
    if (y == 0)
       chByte = ROW1;
    else if (y ==1 )
       chByte = ROW2;
    else if (y ==2 )
       chByte = ROW3;
    else
       chByte = ROW4;

    chByte+=x;
    lcdSendCommand(chByte);
}

// Puts a charachter on LCD starting from ("row", "column") position
void lcdPutCharXY(UINT8 x, UINT8 y, UINT8 charachter)
{
    lcdGotoXY(x,y);
    lcdPutChar(charachter);
}

// Puts a string on LCD starting from ("row", "column") position
void lcdPutStringXY (UINT8 x, UINT8 y, char* string)
{
    lcdGotoXY(x,y);
    lcdPutString(string);
}

// Puts a string on LCD
void lcdPutString (char* string)
{
    char chIndex;
    chIndex = 0;
    while(string[chIndex]!='\0')
    {
        lcdPutChar(string[chIndex]);
        chIndex++;
    }
}

static void lcdEN_Strobe (void)
{
    LCD_EN = 1;
    Nop();
    LCD_EN = 0;
}

// Sends command to LCD
static void lcdSendCommand(UINT8 Command)
{
    LCD_RS = 0;
    lcdSendByte(Command);
}

// Sends data to LCD
static void lcdSendData(UINT8 Data)
{
    LCD_RS = 1;
    lcdSendByte(Data);
}

// Sends byte to LCD
static void lcdSendByte(UINT8 iByte)
{
    UINT8 iTmp;

    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | ((iByte & 0xF0)>>4);
    // Enter in 4 bit mode
    mcpWrite(GPIO,iTmp);
    lcdEN_Strobe();

    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | (iByte & 0x0F);
    // Enter in 4 bit mode
    mcpWrite(GPIO,iTmp);
    lcdEN_Strobe();
}

void lcdPutCGRAMCharPos(char* GraphicChar, char DisplayPosition)
{
    UINT8 iNdx;

    lcdSendCommand(0x40+8*DisplayPosition);
    for(iNdx=0;iNdx<8;iNdx++)
        lcdPutChar(GraphicChar[iNdx]);
}

#define lcdClear lcdSendCommand(LCD_CLEAR)

/*
This Delay_ms routine is generated by
http://www.golovchenko.org/cgi-bin/delay (December 7, 2005 version)
See also various delay routines at
http://www.piclist.com/techref/microchip/delays.htm
*/

//void Delay_ms (unsigned int deltime){}
