#include "lcd.h"
#include <mcpi2c.h>

static void LCD_EN_Strobe(void);
static void LCD_SendCommand(UINT8);
static void LCD_SendData(UINT8);
static void LCD_SendByte(UINT8);

// Puts a charachter on LCD
#define LCD_PutChar(x) LCD_SendData(x)

// LCD Function
void LCD_Init(void)
{
    UINT8 iNdx,iTmp;

    //Delay_ms(5);

    // Reset Sequence
    LCD_EN = 0;
    LCD_RS = 0;

    // Enter in 4 bit mode
    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | 0x03;
    mcpWrite(GPIO,iTmp);
    for(iNdx=1;iNdx<=3;iNdx++)
    {
        LCD_EN_Strobe();
        //Delay_ms(5);
    }

    iTmp = (iTmp & 0xF0) | 0x02;
    mcpWrite(GPIO,iTmp);
    LCD_EN_Strobe();

    LCD_SendCommand(0x28); // 4-bit mode, 2 lines display, font 5x8 pixels
    LCD_SendCommand(0x06); // Increment, no shift

    // Display ON, Cursor OFF, Blink OFF
    LCD_SendCommand(0x0C);
    LCD_SendCommand(0x01);
    LCD_SendCommand(0x03);
}

// Moves the cursor to ("row", "column") position
void LCD_GotoXY(UINT8 x, UINT8 y)
{
    UINT8 chByte;
    if (y == 0)
       chByte = ROW1;
    else if (y ==1 )
       chByte = ROW2;
    else if (y ==2 )
       chByte = ROW3;
    else
       chByte = ROW4;

    chByte+=x;
    LCD_SendCommand(chByte);
}

// Puts a charachter on LCD starting from ("row", "column") position
void LCD_PutCharXY(UINT8 x, UINT8 y, UINT8 charachter)
{
    LCD_GotoXY(x,y);
    LCD_PutChar(charachter);
}

// Puts a string on LCD starting from ("row", "column") position
void LCD_PutStringXY (UINT8 x, UINT8 y, char* string)
{
    LCD_GotoXY(x,y);
    LCD_PutString(string);
}

// Puts a string on LCD
void LCD_PutString (char* string)
{
    char chIndex;
    chIndex = 0;
    while(string[chIndex]!='\0')
    {
        LCD_PutChar(string[chIndex]);
        chIndex++;
    }
}

static void LCD_EN_Strobe (void)
{
    LCD_EN = 1;
    Nop();
    LCD_EN = 0;
}

// Sends command to LCD
static void LCD_SendCommand(UINT8 Command)
{
    LCD_RS = 0;
    LCD_SendByte(Command);
}

// Sends data to LCD
static void LCD_SendData(UINT8 Data)
{
    LCD_RS = 1;
    LCD_SendByte(Data);
}

// Sends byte to LCD
static void LCD_SendByte(UINT8 iByte)
{
    UINT8 iTmp;

    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | ((iByte & 0xF0)>>4);
    // Enter in 4 bit mode
    mcpWrite(GPIO,iTmp);
    LCD_EN_Strobe();

    iTmp = mcpRead(GPIO);
    iTmp = (iTmp & 0xF0) | (iByte & 0x0F);
    // Enter in 4 bit mode
    mcpWrite(GPIO,iTmp);
    LCD_EN_Strobe();
}

void LCD_PutCGRAMCharPos(char* GraphicChar, char DisplayPosition)
{
    UINT8 iNdx;

    LCD_SendCommand(0x40+8*DisplayPosition);
    for(iNdx=0;iNdx<8;iNdx++)
        LCD_PutChar(GraphicChar[iNdx]);
}

#define LCD_Clear LCD_SendCommand(LCD_CLEAR)

/*
This Delay_ms routine is generated by
http://www.golovchenko.org/cgi-bin/delay (December 7, 2005 version)
See also various delay routines at
http://www.piclist.com/techref/microchip/delays.htm
*/

//void Delay_ms (unsigned int deltime){}
